// apps/docs/.vitepress/theme/ExperimentalBadge.vue
<!--
  ExperimentalBadge

  A reusable callout for docs pages that describe features still under
  active construction. Two display modes:

  - inline  → small pill, drops next to a heading or in tables
  - block   → full callout with title + description (default)

  Usage in markdown:

      <ExperimentalBadge />                                  <!-- block, default copy -->
      <ExperimentalBadge mode="inline" />                    <!-- inline pill          -->
      <ExperimentalBadge title="Battles" description="..." /> <!-- override copy        -->
-->
<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  mode?: 'block' | 'inline'
  title?: string
  description?: string
  /** Optional permalink to a tracking issue / roadmap page */
  trackingUrl?: string
  trackingLabel?: string
}

const props = withDefaults(defineProps<Props>(), {
  mode: 'block',
  title: 'Experimental',
  description:
    'This area is under active construction. Behaviour, APIs and UI may change without notice — try it, but expect rough edges and missing tests.',
  trackingUrl: '',
  trackingLabel: 'Track progress',
})

const isInline = computed(() => props.mode === 'inline')
</script>

<template>
  <span
    v-if="isInline"
    class="lf-exp-pill"
    role="status"
    :title="description"
  >
    <span class="lf-exp-pill__dot" aria-hidden="true" />
    <span class="lf-exp-pill__label">{{ title }}</span>
  </span>

  <aside
    v-else
    class="lf-exp-callout"
    role="note"
    aria-label="Experimental feature"
  >
    <div class="lf-exp-callout__icon" aria-hidden="true">
      <!-- Beaker / lab icon: communicates "we're brewing this" -->
      <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">
        <path d="M9 3h6" />
        <path d="M10 3v5.5L5.2 17.4A2 2 0 0 0 7 20.5h10a2 2 0 0 0 1.8-3.1L14 8.5V3" />
        <path d="M7.4 14h9.2" />
      </svg>
      <span class="lf-exp-callout__pulse" aria-hidden="true" />
    </div>

    <div class="lf-exp-callout__body">
      <div class="lf-exp-callout__title">
        <span class="lf-exp-callout__label">{{ title }}</span>
        <span class="lf-exp-callout__chip">Under construction</span>
      </div>
      <p class="lf-exp-callout__desc">{{ description }}</p>
      <a
        v-if="trackingUrl"
        :href="trackingUrl"
        class="lf-exp-callout__link"
        target="_blank"
        rel="noopener noreferrer"
      >
        {{ trackingLabel }}
        <svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M6 3h7v7" />
          <path d="M13 3 4 12" />
        </svg>
      </a>
    </div>
  </aside>
</template>

<style scoped>
/* ───────────────── Inline pill ───────────────── */
.lf-exp-pill {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  padding: 0.15rem 0.55rem;
  border-radius: 999px;
  font-size: 0.72rem;
  font-weight: 600;
  letter-spacing: 0.01em;
  line-height: 1.4;
  color: #92660a;
  background: rgba(255, 222, 89, 0.22);
  border: 1px solid rgba(255, 222, 89, 0.55);
  vertical-align: middle;
  cursor: help;
}

.lf-exp-pill__dot {
  width: 6px;
  height: 6px;
  border-radius: 999px;
  background: #f59e0b;
  box-shadow: 0 0 0 0 rgba(245, 158, 11, 0.5);
  animation: lf-exp-pulse 1.8s ease-in-out infinite;
}

html.dark .lf-exp-pill {
  color: #ffde59;
  background: rgba(255, 222, 89, 0.10);
  border-color: rgba(255, 222, 89, 0.35);
}

/* ───────────────── Block callout ───────────────── */
.lf-exp-callout {
  position: relative;
  display: flex;
  align-items: flex-start;
  gap: 0.85rem;
  padding: 0.95rem 1.05rem;
  margin: 1.1rem 0 1.4rem;
  border-radius: 12px;
  border: 1px solid rgba(255, 222, 89, 0.55);
  background:
    repeating-linear-gradient(
      135deg,
      rgba(255, 222, 89, 0.06) 0 14px,
      rgba(255, 222, 89, 0.12) 14px 28px
    ),
    rgba(255, 252, 230, 0.65);
  color: var(--vp-c-text-1);
  overflow: hidden;
}

.lf-exp-callout::before {
  content: '';
  position: absolute;
  inset: 0 auto 0 0;
  width: 3px;
  background: linear-gradient(180deg, #ffde59 0%, #f59e0b 100%);
}

html.dark .lf-exp-callout {
  border-color: rgba(255, 222, 89, 0.30);
  background:
    repeating-linear-gradient(
      135deg,
      rgba(255, 222, 89, 0.04) 0 14px,
      rgba(255, 222, 89, 0.08) 14px 28px
    ),
    rgba(38, 30, 6, 0.45);
}

.lf-exp-callout__icon {
  position: relative;
  flex: 0 0 auto;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border-radius: 10px;
  background: rgba(255, 222, 89, 0.25);
  color: #92660a;
  margin-top: 1px;
}

html.dark .lf-exp-callout__icon {
  background: rgba(255, 222, 89, 0.15);
  color: #ffde59;
}

.lf-exp-callout__pulse {
  position: absolute;
  top: -3px;
  right: -3px;
  width: 9px;
  height: 9px;
  border-radius: 999px;
  background: #f59e0b;
  box-shadow: 0 0 0 0 rgba(245, 158, 11, 0.6);
  animation: lf-exp-pulse 1.8s ease-in-out infinite;
}

.lf-exp-callout__body { flex: 1 1 auto; min-width: 0; }

.lf-exp-callout__title {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 0.25rem;
}

.lf-exp-callout__label {
  font-weight: 700;
  font-size: 0.95rem;
  letter-spacing: 0.005em;
  color: var(--vp-c-text-1);
}

.lf-exp-callout__chip {
  display: inline-flex;
  align-items: center;
  padding: 0.1rem 0.5rem;
  border-radius: 999px;
  font-size: 0.68rem;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: #92660a;
  background: rgba(255, 222, 89, 0.35);
}

html.dark .lf-exp-callout__chip {
  color: #ffde59;
  background: rgba(255, 222, 89, 0.18);
}

.lf-exp-callout__desc {
  font-size: 0.88rem;
  line-height: 1.55;
  color: var(--vp-c-text-2);
  margin: 0;
}

.lf-exp-callout__link {
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  margin-top: 0.55rem;
  font-size: 0.82rem;
  font-weight: 600;
  color: #92660a;
  text-decoration: none;
}

html.dark .lf-exp-callout__link { color: #ffde59; }

.lf-exp-callout__link:hover { text-decoration: underline; }

/* ───────────────── Shared pulse ───────────────── */
@keyframes lf-exp-pulse {
  0%, 100% { box-shadow: 0 0 0 0 rgba(245, 158, 11, 0.5); }
  50%      { box-shadow: 0 0 0 6px rgba(245, 158, 11, 0); }
}

@media (prefers-reduced-motion: reduce) {
  .lf-exp-pill__dot,
  .lf-exp-callout__pulse { animation: none; }
}
</style>

// libs/ui/components/src/lib/ExperimentalBadge.tsx
import React from 'react'
import { FlaskConical, ExternalLink } from 'lucide-react'

export type ExperimentalBadgeMode = 'block' | 'inline'

export interface ExperimentalBadgeProps {
  /**
   * `block`  — full callout with title + description (default). Use it once at
   *            the top of an experimental page or above an experimental section.
   * `inline` — small pill suitable for headings, tabs, table cells, or nav items.
   */
  mode?: ExperimentalBadgeMode
  /** Title shown on the badge. Defaults to "Experimental". */
  title?: string
  /**
   * Description for the block mode (ignored in inline mode where it becomes a tooltip).
   * Keep it ≤ 220 chars: it sits next to a heading.
   */
  description?: string
  /** Optional permalink (issue, RFC, roadmap). Renders a "Track progress" link. */
  trackingUrl?: string
  trackingLabel?: string
  className?: string
}

/**
 * ExperimentalBadge
 *
 * Visual marker for features that are wired up but not yet hardened by tests
 * or polish passes. Designed so users feel invited to try the feature while
 * understanding that rough edges are expected.
 */
export const ExperimentalBadge = React.forwardRef<HTMLDivElement, ExperimentalBadgeProps>(
  function ExperimentalBadge(
    {
      mode = 'block',
      title = 'Experimental',
      description = "This area is under active construction. It works, but it hasn't been hardened with tests yet — please try it and report anything that feels off.",
      trackingUrl,
      trackingLabel = 'Track progress',
      className = '',
    },
    ref,
  ) {
    if (mode === 'inline') {
      return (
        <span
          ref={ref as React.Ref<HTMLDivElement> & React.Ref<HTMLSpanElement>}
          role="status"
          title={description}
          className={
            'inline-flex items-center gap-1 align-middle rounded-full ' +
            'px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ' +
            'border border-primary-yellow-500/55 ' +
            'bg-primary-yellow-500/15 text-primary-yellow-800 ' +
            'dark:bg-primary-yellow-500/10 dark:text-primary-yellow-300 dark:border-primary-yellow-500/30 ' +
            className
          }
        >
          <span
            aria-hidden="true"
            className="inline-block h-1.5 w-1.5 rounded-full bg-primary-yellow-600 dark:bg-primary-yellow-400 animate-pulse motion-reduce:animate-none"
          />
          {title}
        </span>
      )
    }

    return (
      <div
        ref={ref}
        role="note"
        aria-label="Experimental feature"
        className={
          'relative flex gap-3 rounded-xl border p-3.5 sm:p-4 overflow-hidden ' +
          'border-primary-yellow-500/40 bg-primary-yellow-500/8 ' +
          'dark:border-primary-yellow-500/25 dark:bg-primary-yellow-500/5 ' +
          className
        }
      >
        {/* Diagonal construction stripes — subtle, behind content */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 opacity-[0.18] dark:opacity-[0.10]"
          style={{
            backgroundImage:
              'repeating-linear-gradient(135deg, currentColor 0 1px, transparent 1px 14px)',
            color: '#ffde59',
          }}
        />
        {/* Left accent bar */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-y-0 left-0 w-[3px] bg-gradient-to-b from-primary-yellow-400 to-primary-yellow-600"
        />

        <div className="relative flex-shrink-0 mt-0.5">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-yellow-500/25 text-primary-yellow-800 dark:bg-primary-yellow-500/15 dark:text-primary-yellow-300">
            <FlaskConical className="h-[18px] w-[18px]" />
          </div>
          <span
            aria-hidden="true"
            className="absolute -top-0.5 -right-0.5 inline-block h-2.5 w-2.5 rounded-full bg-primary-yellow-500 ring-2 ring-white dark:ring-greyscale-900 animate-pulse motion-reduce:animate-none"
          />
        </div>

        <div className="relative min-w-0 flex-1">
          <div className="mb-1 flex flex-wrap items-center gap-2">
            <p className="text-sm font-semibold leading-tight text-greyscale-900 dark:text-greyscale-50">
              {title}
            </p>
            <span className="inline-flex items-center rounded-full bg-primary-yellow-500/35 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-primary-yellow-900 dark:bg-primary-yellow-500/20 dark:text-primary-yellow-300">
              Under construction
            </span>
          </div>
          <p className="text-[13px] leading-relaxed text-greyscale-700 dark:text-greyscale-300">
            {description}
          </p>
          {trackingUrl && (
            <a
              href={trackingUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-1.5 inline-flex items-center gap-1 text-xs font-semibold text-primary-yellow-800 hover:underline dark:text-primary-yellow-300"
            >
              {trackingLabel}
              <ExternalLink className="h-3 w-3" />
            </a>
          )}
        </div>
      </div>
    )
  },
)

ExperimentalBadge.displayName = 'ExperimentalBadge'
